<#
.SYNOPSIS
Generate launcher/src/version_generated.h from git tags.

.DESCRIPTION
Resolution order:
  1. $env:LAUNCHER_VERSION (verbatim display string; parse leading vX.Y[.Z] for ints).
  2. git describe --tags --long --dirty (parse vX.Y.Z-N-gSHA[-dirty]).
  3. git rev-parse --short HEAD: "dev+g<sha>[.dirty]" (dirty from git status --porcelain,
     since we're not using describe's own --dirty here).
  4. Fallback: 0,0,0,0 and "dev-untagged" (no git, or not a repo).

Write-if-different so unchanged content doesn't churn the resource recompile.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'

function Parse-TagInts {
    param([string]$Tag)
    # Tag like "v0.9.5", "0.9.5", "v0.9", "v0.9.5-rc1". Strip leading 'v', drop any suffix
    # after the first non-digit-or-dot, then pad to 3 ints.
    $t = $Tag -replace '^v', ''
    $t = ($t -split '[^0-9.]')[0]
    $parts = ($t -split '\.') | Where-Object { $_ -ne '' }
    $ints = [int[]]@(0, 0, 0)
    for ($i = 0; $i -lt [Math]::Min(3, $parts.Length); $i++) {
        $ints[$i] = [int]$parts[$i]
    }
    return $ints
}

$ints = @(0, 0, 0, 0)
$displayStr = 'dev-untagged'

if ($env:LAUNCHER_VERSION) {
    # Explicit override (CI sets this from github.ref_name on tag builds).
    $displayStr = $env:LAUNCHER_VERSION -replace '^v', ''
    $tagInts = Parse-TagInts $env:LAUNCHER_VERSION
    $ints = @($tagInts[0], $tagInts[1], $tagInts[2], 0)
} else {
    # Try git describe.
    $described = $null
    try {
        $described = (& git describe --tags --long --dirty 2>$null) | Out-String
        $described = $described.Trim()
    } catch {
        $described = $null
    }
    if ($described -and $LASTEXITCODE -eq 0) {
        # Format: vX.Y.Z-N-gSHA[-dirty] or vX.Y-N-gSHA[-dirty].
        # `-dirty` suffix means working tree has uncommitted changes.
        # Pre-release tags like 'v1.0.0-rc1' do NOT match (the rc1 contains
        # non-numerics before the -N- commit count); they fall through to
        # the dev-untagged fallback. Use $env:LAUNCHER_VERSION to override.
        if ($described -match '^(v[0-9.]+)-([0-9]+)-(g[0-9a-f]+)(-dirty)?$') {
            $tag = $matches[1]
            $commitsAhead = [int]$matches[2]
            $sha = $matches[3]
            $dirty = if ($matches[4]) { '.dirty' } else { '' }
            $tagInts = Parse-TagInts $tag
            $ints = @($tagInts[0], $tagInts[1], $tagInts[2], $commitsAhead)
            $baseStr = ($tag -replace '^v', '')
            if ($commitsAhead -eq 0 -and -not $dirty) {
                $displayStr = $baseStr
            } else {
                $displayStr = "$baseStr+$commitsAhead.$sha$dirty"
            }
        } else {
            Write-Warning "gen-version: git describe output '$described' did not match the expected format (vX.Y[.Z]-N-gSHA[-dirty]); falling back to dev+g<sha>. Set `$env:LAUNCHER_VERSION to override."
        }
    }

    # No usable tag (git describe failed, or its output didn't match): fall back to a
    # revision-derived version instead of the uninformative bare "dev-untagged", using
    # the same g<sha>/.dirty spelling as the tagged-build format above.
    if ($ints[3] -eq 0 -and $displayStr -eq 'dev-untagged') {
        $sha = $null
        try {
            $sha = (& git rev-parse --short HEAD 2>$null) | Out-String
            $sha = $sha.Trim()
        } catch {
            $sha = $null
        }
        if ($sha -and $LASTEXITCODE -eq 0) {
            # `git status --porcelain` rather than `git describe --dirty`'s own check,
            # since this path runs when describe didn't produce a usable result at all.
            # Observed in this repo's colocated jj working copy: this reports dirty on
            # every build, same as git describe --dirty does here (see the T1 notes) -
            # jj doesn't move the colocated git HEAD/index to match @ on every snapshot,
            # so git always sees a diff against its last-known commit. Harmless: it just
            # means dev builds from a jj checkout always carry .dirty, tag builds are
            # unaffected (they go through $env:LAUNCHER_VERSION in CI).
            $dirty = ''
            try {
                $status = (& git status --porcelain 2>$null) | Out-String
                if ($status.Trim().Length -gt 0) { $dirty = '.dirty' }
            } catch {
                # Treat an unreadable status as clean; the sha alone is still useful.
            }
            $displayStr = "dev+g$sha$dirty"
        }
    }
}

$intsCsv = ($ints -join ',')
$content = @"
// Auto-generated by gen-version.ps1. Do not commit.
#define LAUNCHER_FILEVERSION_INTS    $intsCsv
#define LAUNCHER_PRODUCTVERSION_INTS $intsCsv
#define LAUNCHER_FILEVERSION_STR     "$displayStr"
#define LAUNCHER_PRODUCTVERSION_STR  "$displayStr"
"@

# Write-if-different: avoid churning rc.exe rebuilds on unchanged version.
$existing = $null
if (Test-Path $OutputPath) {
    $existing = Get-Content -Raw -LiteralPath $OutputPath
}
if ($existing -ne ($content + "`r`n")) {
    Set-Content -LiteralPath $OutputPath -Value $content -Encoding UTF8
    Write-Host "gen-version: wrote $OutputPath ($displayStr -> $intsCsv)"
} else {
    Write-Host "gen-version: unchanged ($displayStr -> $intsCsv)"
}
